version: '3.8'

services:
  face-recognition:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./face_recognition.db:/app/face_recognition.db
      - ./users:/app/users
      - ./models:/app/models
    environment:
      - FLASK_ENV=production
      - PORT=5000
    restart: unless-stopped
